### ISSUE TITLE
v2 roadmap

### ISSUE THREAD

**Issue by Apollo3zehn** [nexus-main/nexus#131]
- [ ] #128: Switch to .NET 9 / C# 13
- [ ] #129: Use the new Lock object
- [ ] #130: Make use of the new partial properties
